const dbName='studynest-db', passKey='studynest-owner-passcode-v1'; let database,pendingFiles=[]; const $=s=>document.querySelector(s);
function hash(value){let h=5381;for(let i=0;i<value.length;i++)h=((h<<5)+h)^value.charCodeAt(i);return String(h>>>0)}
function openDatabase(){return new Promise((resolve,reject)=>{const r=indexedDB.open(dbName,1);r.onupgradeneeded=()=>r.result.createObjectStore('documents',{keyPath:'id'});r.onsuccess=()=>{database=r.result;resolve()};r.onerror=()=>reject(r.error)})}
function getAll(){return new Promise((resolve,reject)=>{const r=database.transaction('documents').objectStore('documents').getAll();r.onsuccess=()=>resolve(r.result.sort((a,b)=>b.addedAt-a.addedAt));r.onerror=()=>reject(r.error)})}
function put(doc){return new Promise((resolve,reject)=>{const r=database.transaction('documents','readwrite').objectStore('documents').put(doc);r.onsuccess=resolve;r.onerror=()=>reject(r.error)})}
function remove(id){return new Promise((resolve,reject)=>{const r=database.transaction('documents','readwrite').objectStore('documents').delete(id);r.onsuccess=resolve;r.onerror=()=>reject(r.error)})}
function esc(text){const d=document.createElement('div');d.textContent=text;return d.innerHTML} function date(t){return new Intl.DateTimeFormat(undefined,{day:'numeric',month:'short',year:'numeric'}).format(new Date(t))} function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}
function isAuthed(){return sessionStorage.getItem('studynest-owner-session')==='yes'} function showDashboard(){ $('#authScreen').hidden=true;$('#dashboard').hidden=false;render() } function setupAuth(){const hasPass=!!localStorage.getItem(passKey);$('#authTitle').textContent=hasPass?'Welcome back, owner':'Set your owner passcode';$('#authHelp').textContent=hasPass?'Enter your passcode to manage study resources.':'Create a passcode for this dashboard. You will use it whenever you add or manage study material on this browser.';$('#confirmWrap').hidden=hasPass;$('#authButton').textContent=hasPass?'Unlock dashboard':'Create owner access'}
$('#authButton').onclick=()=>{const pass=$('#passcodeInput').value,confirm=$('#confirmInput').value,stored=localStorage.getItem(passKey);$('#authError').textContent='';if(pass.length<6){$('#authError').textContent='Use at least 6 characters.';return}if(stored){if(hash(pass)!==stored){$('#authError').textContent='That passcode is not correct.';return}}else{if(pass!==confirm){$('#authError').textContent='The passcodes do not match.';return}localStorage.setItem(passKey,hash(pass))}sessionStorage.setItem('studynest-owner-session','yes');showDashboard()};
async function render(){const docs=await getAll();$('#adminInfo').textContent=docs.length?`${docs.length} PDF${docs.length===1?'':'s'} visible to students in this browser.`:'No PDFs uploaded yet.';$('#adminEmpty').hidden=!!docs.length;$('#adminGrid').innerHTML=docs.map(d=>`<article class="doc-card"><div class="doc-preview"><span class="pdf-mark">PDF</span><span class="subject-badge">${esc(d.subject)}</span></div><div class="doc-info"><p class="doc-name" title="${esc(d.label||d.name)}">${esc(d.label||d.name)}</p><p class="doc-meta">${esc(d.type)} · ${date(d.addedAt)}</p><div class="admin-grid-actions"><span class="doc-meta">Published</span><button class="delete-button" data-delete="${d.id}">Remove</button></div></div></article>`).join('')}
function startUpload(files){pendingFiles=[...files].filter(f=>f.type==='application/pdf'||f.name.toLowerCase().endsWith('.pdf'));if(!pendingFiles.length)return toast('Please choose PDF files only.');setDetails()};function setDetails(){const f=pendingFiles[0];if(!f)return;$('#dialogFileName').textContent=f.name;$('#dialogLabel').value='';if(!$('#detailsDialog').open)$('#detailsDialog').showModal()};async function save(){const f=pendingFiles.shift();await put({id:crypto.randomUUID(),name:f.name,label:$('#dialogLabel').value.trim(),subject:$('#dialogSubject').value,type:$('#dialogType').value,addedAt:Date.now(),file:f});if(pendingFiles.length)setDetails();else{$('#detailsDialog').close();toast('PDF published to your library.')}render()}
$('#fileInput').onchange=e=>{startUpload(e.target.files);e.target.value=''};$('#browseButton').onclick=e=>{e.stopPropagation();$('#fileInput').click()};const zone=$('#dropZone');['dragenter','dragover'].forEach(name=>zone.addEventListener(name,e=>{e.preventDefault();zone.classList.add('dragging')}));['dragleave','drop'].forEach(name=>zone.addEventListener(name,e=>{e.preventDefault();zone.classList.remove('dragging')}));zone.ondrop=e=>startUpload(e.dataTransfer.files);zone.onclick=()=>$('#fileInput').click();zone.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('#fileInput').click()}};$('#detailsForm').onsubmit=e=>{if(e.submitter?.id==='saveDocument'){e.preventDefault();save()}};$('#detailsDialog').onclose=()=>{pendingFiles=[]};$('#adminGrid').onclick=async e=>{const id=e.target.dataset.delete;if(id&&confirm('Remove this PDF from the student library?')){await remove(id);toast('PDF removed.');render()}};$('#signOut').onclick=()=>{sessionStorage.removeItem('studynest-owner-session');location.reload()};
openDatabase().then(()=>{if(isAuthed())showDashboard();else setupAuth()}).catch(()=>toast('Could not open the local PDF library.'));
